version: '3'

services:
    db_auth-service:
      container_name: mongo_container
      image: db-service
      ports:
        - "27017:27017"
      networks:
        - auth-mongo
      volumes:
        - mongo-vol:/data/db

    auth-service:
      container_name: auth_container
      image: auth-service
      ports: 
        - "5000:5000"
      networks:
        - auth-mongo
        - auth-ftp
        - auth-http

networks: 
    auth-mongo:
    auth-ftp:
    auth-http:

volumes:
  mongo-vol:
  http_ftp-vol:
    

