version: '3'

services:
    db_auth-service:
      container_name: mongo_container
      image: db-service
      ports:
        - "27017:27017"
      networks:
        - auth-mongo
      volumes:
        - mongo-vol:/data/db

    auth-service:
      container_name: auth_container
      image: auth-service
      ports: 
        - "5000:5000"
      networks:
        - auth-mongo
        - auth-ftp
        - auth-http

    http-service:
      container_name: http_container
      image: http-service
      networks: 
        - auth-http
      ports: 
        - "8888:8888"
      volumes:
        - http_ftp-vol:/usr/src/http

    ftp-service:
      container_name: ftp_container
      image: ftp-service
      networks:
        - auth-ftp
      ports:
        - "21:21"
      volumes:
        - http_ftp-vol:/usr/src/ftp

networks: 
    auth-mongo:
    auth-ftp:
    auth-http:

volumes:
  mongo-vol:
  http_ftp-vol:
    

