version: '3'

services:
    db_auth-service:
      container_name: mongo_container
      image: db-service
      ports:
        - "27017:27017"
      networks:
        - auth-mongo
      volumes:
        - mongo-vol:/data/db
        - /home/vagrant/VR_TP2/logs/db/:/var/log/mongodb/

    auth-service:
      container_name: auth_container
      image: auth-service
      ports: 
        - "5000:5000"
      networks:
        - auth-mongo
        - auth-ftp
        - auth-http
      volumes:
        - /home/vagrant/VR_TP2/logs/auth:/auth-server/logs

    http-service:
      container_name: http_container
      image: http-service
      networks: 
        - auth-http
      ports: 
        - "8888:8888"
      volumes:
        - http_ftp-vol:/usr/src/http
        - /home/vagrant/VR_TP2/logs/http:/http-server/logs

    ftp-service:
      container_name: ftp_container
      image: ftp-service
      networks:
        - auth-ftp
      ports:
        - "2121:2121"
      volumes:
        - http_ftp-vol:/usr/src/ftp
        - /home/vagrant/VR_TP2/logs/ftp:/ftp-server/logs

networks: 
    auth-mongo:
    auth-ftp:
    auth-http:

volumes:
  mongo-vol:
    driver: local
  http_ftp-vol:
    driver: local
    

